substitutions:
  _REGION: europe-west9
  _REGION_SCHEDULAR: europe-west3
  _REPO: data-api
  _IMAGE: extraction-job


steps:
# Build Docker
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
    - 'data-extraction'

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'

# Déployer Cloud Run via Terraform
- name: 'hashicorp/terraform:1.6'
  entrypoint: sh
  args:
    - -c
    - |
      cd terraform/platform/applications/data-jobs
      terraform init
      terraform apply -auto-approve \
        -var="image_extraction_from_data_source_api_tag=$SHORT_SHA" \
        -var="extraction_job_image_name=$_IMAGE" \
        -var="repo_name=$_REPO" \
        -var="region=$_REGION" \
        -var="region_schedular=$_REGION_SCHEDULAR" \



options:
  logging: CLOUD_LOGGING_ONLY
