substitutions:
  _REGION: europe-west9
  _REGION_SCHEDULAR: europe-west3
  _REPO: data-api
  _IMAGE: population-job


steps:
# Build Docker
- name: 'gcr.io/cloud-builders/docker'
  args:
    - build
    - '-t'
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
    - 'data-population'
  id : "building image of the population job"

# Push image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - push
    - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:$SHORT_SHA'
  id : "pushing image of the population job in artefact registry"

# Déployer Cloud Run via Terraform
- name: 'hashicorp/terraform:1.6'
  entrypoint: sh
  args:
    - -c
    - |
      cd terraform/platform/applications/data-jobs
      terraform init
      terraform apply -auto-approve \
        -target=module.cloud_run_job_data_processing \
        -var="image_population_sales_table_tag=$SHORT_SHA" \
        -var="population_job_image_name=$_IMAGE" \
        -var="repo_name=$_REPO" \
        -var="region=$_REGION" \
        -var="region_schedular=$_REGION_SCHEDULAR"
  id : "Building cloud run population job"



options:
  logging: CLOUD_LOGGING_ONLY
